<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>register</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f330acac-d5c7-4a39-911c-b763a303c097</testSuiteGuid>
   <testCaseLink>
      <guid>4e92bdcd-927a-4b7e-b8b4-41bdfbfc199e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DemoBlaze/common/sign up</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f5718f49-f8b6-4f7c-885e-1e86bba696e6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/demoblaze</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96ab718f-a09d-46c8-9749-2e958651bdcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8ff9f40-5e24-4d55-be2f-2b58cd4d37db</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
